[package]
name = "dsapiforwardedfor"
version = "0.1.0"
authors = ["Jesse Gallagher <jesse@secondfoundation.org>"]
edition = "2018"

[lib]
name = "dsapiforwardedfor"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.56.0"

[dependencies]
